server:
  port: 8081



spring:
  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.83.56:3306/item?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 1122Zh,.


    mybatis:
      type-aliases-package: com.wp.weipu.entity
      mapper-locations: classpath:mapper/**/*.xml
      base-package: com.wp.weipu.mapper

    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      servlet:
        content-type: text/html